name: Android-Чтосмотреть-看看
on:
  workflow_dispatch:
  schedule:
    - cron: '2 0 * * *'
  watch:
    types: started
  repository_dispatch:
    types: bean_change
jobs:
  build:

    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
        zqlookStartbody: ${{ secrets.ZQLOOKSTARTBODY }}
        zqlookStartbody2: ${{ secrets.ZQLOOKSTARTBODY2 }}
        zqlookStartbody3: ${{ secrets.ZQLOOKSTARTBODY3 }}
        zqlookStartbody4: ${{ secrets.ZQLOOKSTARTBODY4 }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: npm install
        run: |
          npm install
      - name: '运行 【Android-Чтосмотреть-birbaxın】'
        if: env.zqlookStartbody
        run: |
          node Android-Чтосмотреть-birbaxın.js
        env:
          zqlookStartbody: ${{ secrets.ZQLOOKSTARTBODY }}
          zq_cookie: ${{ secrets.ZQ_COOKIE }}

      - name: '运行 【Android-Чтосмотреть-birbaxın二】'
        if: env.zqlookStartbody2
        run: |
          node Task/Youth_Read.js
        env:
          zqlookStartbody: ${{ secrets.ZQLOOKSTARTBODY2 }}
          zq_cookie: ${{ secrets.ZQ_COOKIE }}

      - name: '运行 【Android-Чтосмотреть-birbaxın三】'
        if: env.zqlookStartbody3
        run: |
          node Task/Youth_Read.js
        env:
          zqlookStartbody: ${{ secrets.ZQLOOKSTARTBODY3 }}
          zq_cookie: ${{ secrets.ZQ_COOKIE }}

      - name: '运行 【Android-Чтосмотреть-birbaxın四】'
        if: env.zqlookStartbody4
        run: |
          node Task/Youth_Read.js
        env:
          zqlookStartbody: ${{ secrets.ZQLOOKSTARTBODY4 }}
          zq_cookie: ${{ secrets.ZQ_COOKIE }}
